from src.utils.param_singleton import Params

# TODO(kezhang@): implement this im params
FANBOOK_BOT_NAME = Params().FANBOOK_BOT_NAME
FANBOOK_BOT_OWNER_NAME = Params().FANBOOK_BOT_OWNER_NAME
FANBOOK_BOT_OWNER_ID = Params().FANBOOK_BOT_OWNER_ID
FANBOOK_BOT_CREATOR_ID = Params().FANBOOK_BOT_CREATOR_ID
FANBOOK_CLIENT_ID = Params().FANBOOK_CLIENT_ID

BASE_URL = 'https://a1.fanbook.mobi/api'
GET_USER_TOKEN_TIMEOUT_COUNT = 3
FANBOOK_GET_ME_URL = f'{BASE_URL}/bot/{Params().FANBOOK_BOT_TOKEN}/getMe'
FANBOOK_SEND_MSG_URL = f'https://a1.fanbook.mobi/api/bot/{Params().FANBOOK_BOT_TOKEN}/sendMessage'  # noqa
DEVICE_ID = f'bot{FANBOOK_CLIENT_ID}'
FANBOOK_VERSION = '1.6.60'
HEAT_BEAT_INTERVAL = 20
PUBLIC_CHANNEL_TYPE = 0
PRIVATE_CHANNEL_TYPE = 3
TEST_BOT_ID = '508069544456466432'
LIMIT_USER_LIST_COUNT = 1000
